# Generated by Django 5.2.15 on 2026-07-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('no_of_guests', models.IntegerField()),
                ('reservation_date', models.DateField()),
                ('reservation_slot', models.TimeField(default='19:00:00')),
            ],
        ),
    ]
